###
GET http://localhost:5185

###
GET http://localhost:5185/games

###
GET http://localhost:5185/games/2

###
POST http://localhost:5185/games
Content-Type: application/json

{
    "name": "The Witcher 8",
    "genreId": "2",
    "price": 19.99,
    "releaseDate": "2011-11-18"
}

###
PUT http://localhost:5185/games/2
Content-Type: application/json

{
   "name": "The Witcher 3",
    "genreId": 2,
    "price": 50.99,
    "releaseDate": "2015-05-19"
}

###
DELETE  http://localhost:5185/games/8
